server:
  port: 8080

  spring:
    datasource:
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      openInView: false
    h2:
      console:
        enabled: true
    flyway:
      enabled: true

logging:
  level:
    com.przemo: DEBUG
    org.flywaydb: DEBUG
