server:
  port: 8080

  spring:
    datasource:
      url: jdbc:h2:mem:game_shop
      driverClassName: org.h2.Driver
      username: as
      password: as
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      openInView: false
    h2:
      console:
        enabled: true
    flyway:
      enabled: true

logging:
  level:
    com.przemo: DEBUG
    org.flywaydb: DEBUG
