spring:
  datasource:
    url: jdbc:h2:mem:game_shop;DB_CLOSE_ON_EXIT=FALSE
    username: as
    password:
management:
  endpoints:
    web:
      exposure:
        include: prometheus
springdoc:
  showActuator: true