filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              container.name: gameshop
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              #include_lines: ['^{']
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
