filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            - contains:
                container.name: gameshop
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              include_lines: ['^{']
output.elasticsearch:
  hosts: ["http://es01:9200"]
  username: "elastic"
  password: "changeme"
