CREATE TABLE IF NOT EXISTS game (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(250) NOT NULL UNIQUE,
  price DECIMAL(9,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS cart (
  id INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS carts_games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cart_id INT NOT NULL,
  game_id INT NOT NULL,
  game_count INT NOT NULL,
  FOREIGN KEY (cart_id) REFERENCES cart(id),
  FOREIGN KEY (game_id) REFERENCES game(id)
);